### ISSUE TITLE
Enable quiet error-ing

### ISSUE THREAD

**Issue by bretty-mcbrettface** [jebena/jebena-python-client#4]
Right now, the client is already spitting out errors that are happening to stdout. I've been swallowing those rather than error catching, and it might be nice to have the script not blow up if that happens. So an option for loud errors would be cool.

**Comment by jpotter** [comment]
@bretty-mcbrettface Does https://github.com/jebena/jebena-python-client/pull/3/files fix this for you? Instead of silencing, this adds a `return_instead_of_raise_on_errors` flag which means you as the caller would have to check for GQL errors.

**Comment by bretty-mcbrettface** [comment]
yeah that seems fine.

**Comment by jpotter** [comment]
@bretty-mcbrettface Actually, slightly better solution coming your way: first off, these were already controllable with setting python's logging level on the `jebenaclient` package, but that's sometimes annoying. More usefully though, I've got a soon-to-commit PR that adds a bool `skip_logging_transient_errors` which may be easier for these cases.
